import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  // get the result from search box and stored it to gif
  const [gif, setGif] = useState('')

  // store the the fetched data in results
  const [results, setResults] = useState([])

  //Update the fetch data when the form is submitted.
  const handleSubmit = async ( event) => {
    event.preventDefault()
    const res = await fetch(`http://localhost:3000/api/gif?q=${gif}`)
    const data = await res.json()
    setResults(data)
  }

  // Update the gif value when the customer typed in search box
  const handleChange = (event) => {
    setGif(event.target.value)
  }



  return (
    <div className={styles.container}>

          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>


          <main className={styles.main}>
              <h1 className={styles.title}>
                Welcome to <a href="https://giphy.com/">Giphy App!</a>
              </h1>

              <div className={styles.inputForm}>
                <form onSubmit={handleSubmit} className='search'>
                  <input value={gif} onChange={handleChange} className={styles.box} placeholder='Search...' type="text"></input>
                  <button className={styles.box} onClick={handleSubmit} >Search</button>
                </form>
              </div>

              <ul className={styles.grid}>
                  {results.map((result) =>{
                    const { id, title, image } = result
                    
                    return (
                        <li key={id} className={styles.card}>
                          <img className={styles.img} src={image} alt='blank'></img>
                          <h2>{title}</h2>
                        </li>
                    )         
                    })}
              </ul>
                   
          </main>


          <footer className={styles.footer}>
              <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                Powered by{' '}
                <span className={styles.logo}>
                  <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </span>
              </a>
          </footer>


    </div>
  )
}
