import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home({ data }) {

  const [gif, setGif] = useState('')

  const handleSubmit = (event) => {
    event.preventDefault()
    
     const getStaticProps = async () => {
      const res = await fetch(`https://api.giphy.com/v1/gifs/search?api_key=RYPX1Dh9ls2o2pcSRqhauIFV2uUGzGok&q=${gif}&limit=9&offset=0&rating=g&lang=en`)
      const data = await res.json()
    
      return {
        props: {
          data
        }
      }
    
    }


    // const { currentTarget = {} } = event;
    // const fields = Array.from(currentTarget?.elements);
    // const fieldQuery = fields.find(field => field.name === 'query');

    // const value = fieldQuery.value || '';
    // const endpoint = `https://api.giphy.com/v1/gifs/search?api_key=RYPX1Dh9ls2o2pcSRqhauIFV2uUGzGok&q=${value}&limit=9&offset=0&rating=g&lang=en`

    // updatePage({
    //   current: endpoint
    // })
  }

  const handleChange = (event) => {
    setGif(event.target.value)
    console.log(gif)
  }


  
  console.log(data)

  return (
    <div className={styles.container}>

          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>


          <main className={styles.main}>
              <h1 className={styles.title}>
                Welcome to <a href="https://giphy.com/">Giphy App!</a>
              </h1>

              <div className={styles.inputForm}>
                <form onSubmit={handleSubmit} className='search'>
                  <input value={gif} onChange={handleChange} className={styles.box} placeholder='Search...' type="text"></input>
                  <button className={styles.box} onClick={handleSubmit} >Search</button>
                </form>
              </div>

              <ul className={styles.grid}>
                  {data.map((gif) =>{
                    const { id, title, image } = gif
                    
                    return (
                        <li key={id} className={styles.card}>
                          <img className={styles.img} src={image} alt='blank'></img>
                          <h2>{title}</h2>
                        </li>
                    )         
                    })}
              </ul>
                   
          </main>


          <footer className={styles.footer}>
              <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                Powered by{' '}
                <span className={styles.logo}>
                  <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </span>
              </a>
          </footer>


    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch('http://localhost:3000/api/gif')
  const data = await res.json()

  return {
    props: {
      data
    }
  }

}