/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import InfiniteScroll from "react-infinite-scroll-component"
import styles from '../styles/Home.module.css'

export default function Home() {
  
  const myKey = 'RYPX1Dh9ls2o2pcSRqhauIFV2uUGzGok';
  //set offset to zero since the api return data from a starting offsetNumber
  let newOffset = 0;
  
  // get the result from search box and stored it to gif
  const [gif, setGif] = useState('')

  // to check if there are more data for infinite scrolling
  const [hasMore, setHasMore] = useState(true)

  // store the the fetched data in results
  const [results, setResults] = useState([])

  //Update the fetch data when the form is submitted.
  const handleSubmit = async ( event) => {
    event.preventDefault()
    const res = await fetch(`./api/gif?q=${gif}&offset=${newOffset}`)
    const data = await res.json()
    setResults(data)
  }

  // Update the gif value when the customer typed in search box
  const handleChange = (event) => {
    setGif(event.target.value)
  }

  //To load more post from infinite scrolling
  const getMorePost = async () =>{
    newOffset += results.length || 0
    console.log("newOffset value", newOffset)

    const res = await fetch(`./api/gif?q=${gif}&offset=${newOffset}`);
    const newPosts = await res.json()
    setResults(results => [...results, ...newPosts])
  }

  


  return (
    <div className={styles.container}>

          <Head>
              <title>Create Giphy App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>


          <main className={styles.main}>
              <div className={styles.layout} >
                <h1 className={styles.title}>
                  Welcome to my <a href="https://giphy.com/">Giphy App!</a>
                </h1>

                <div className={styles.inputForm}>
                  <form onSubmit={handleSubmit} className='search'>
                    <input value={gif} onChange={handleChange} className={styles.box} placeholder='Search...' type="text"></input>
                    <button className={styles.box} onClick={handleSubmit} >Search</button>
                  </form>
                </div> 
              </div>

              <InfiniteScroll
                dataLength={results.length}
                next={getMorePost}
                hasMore={hasMore}
              >
                <ul className={styles.grid}>
                    {results.map((result) =>{
                      const { id, title, image } = result
                      
                      return (
                          <li key={id} className={styles.card}>
                            <div  className={styles.imgCont} >
                             <video className={styles.img} src={image} /> 
                            </div>
                          </li>
                      )         
                      })}
                </ul>
              </InfiniteScroll>

                   
          </main>


    </div>
  )
}
